name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      should_succeed:
        description: 'Should the unit tests succeed?'
        required: true
        type: boolean

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      should_succeed: ${{ contains(github.event.inputs.should_succeed, 'true') }}

  check-for-review:
    permissions: write-all
    needs: run-unit-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Run a one-line script
        run: echo "${{ needs.run-unit-tests.result }}" >> $GITHUB_STEP_SUMMARY

      - name: Create or update environment
        run: |
          if [ "${{ needs.run-unit-tests.result }}" != "success" ]; then
            curl -X PUT \
              -H "Authorization: token ${{ secrets.RESULT_CHECK_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/environments/staging \
              -d '{
                "reviewers": ["thedave42"]
              }'
          else
            curl -X PUT \
              -H "Authorization: token ${{ secrets.RESULT_CHECK_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/environments/staging \
              -d '{
                "reviewers": []
              }'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.RESULT_CHECK_TOKEN }}Y

  