name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      should_succeed:
        description: 'Should the unit tests succeed?'
        required: true
        type: boolean

jobs:
  run-unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      should_succeed: ${{ github.event.inputs.should_succeed }}

  second-job:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"

  