# This will be a reusable workflow that will either fail or pass based on an input parameter
# 1. the input parameter will be a boolean that indicates whether the workflow should succeed or fail
# 2. the workflow will have a single job that runs a script that will either exit with a 0 or 1
# 3. the job will use the input parameter to determine the exit code of the script

name: Unit Tests
on:
  workflow_call:
    inputs:
      should_succeed:
        description: 'Boolean that indicates whether the workflow should succeed or fail'
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          if ${{ inputs.should_succeed }}; then
            exit 0
          else
            exit 1
          fi
